apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myapp.servers.k8s.nestgroup.net
    http:
      paths:
      - backend:
          serviceName: myapp
          servicePort: 80
